services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "$IP_ADDRESS:8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    depends_on:
      - pgdb
      - migration
      - minio

  migration:
    build: .
    container_name: migration
    command: bash -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py flush --no-input && python manage.py fill_db"
    volumes:
      - ./:/usr/src/app
    depends_on:
      pgdb:
        condition: service_healthy
    links:
      - pgdb

  pgdb:
    image: postgres:16.0-alpine
    container_name: pgdb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: volume
        source: pgdbdata
        target: /var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
       - pgadmin:/var/www/nest_test/docker-volumes/pgadmin
       - ./servers.json:/pgadmin4/servers.json
    ports:
      - "$IP_ADDRESS:5050:80"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data

  createbucket:
    image: minio/mc:latest
    container_name: createbucket
    depends_on:
      - minio
    volumes:
      - ./app/static/images:/images
    entrypoint: >
      /bin/sh -c "
        until (mc alias set myminio http://minio:9000 minio minio123 2>/dev/null) do echo '...' && sleep 1; done;
        mc mb myminio/images;
        mc anonymous set public myminio/images;
        mc cp --recursive /images/ myminio/images;
        exit 0;
      "

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "$IP_ADDRESS:9000:9000"
      - "$IP_ADDRESS:9001:9001"
    env_file:
      - .env
    depends_on:
      - minio

volumes:
  pgdbdata: null
  pgadmin:
  minio-data: